### ISSUE TITLE
travis: Enable travis ci for ppc64le 

### ISSUE THREAD

**Issue by nitkon** [kata-containers/osbuilder#122]

**Comment by nitkon** [comment]
@jodh-intel 
A couple of things:
1. Since clearlinux is not on Power, I shall be skipping the test for it for ppc64le.
2. When I run CI for ppc64le for AGENT_INIT=yes , I get a repetitive timeout bcoz of which travis fails. 

```
$ travis_wait .ci/run.sh
Timeout (20 minutes) reached. Terminating ".ci/run.sh"
The command .ci/run.sh exited with 137.
```

**Comment by jodh-intel** [comment]
Hi @nitkon,

> 1. Since clearlinux is not on Power, I shall be skipping the test for it for ppc64le.

Sure.

> 2. When I run CI for ppc64le for AGENT_INIT=yes , I get a repetitive timeout bcoz of which travis fails.

Could you get further details on what operation is causing this to timeout?

**Comment by nitkon** [comment]
@jodh-intel : Here are the [logs](https://travis-ci.org/nitkon/osbuilder/jobs/397310850). The tests are exceeding the 20min timeout limit.

**Comment by grahamwhaley** [comment]
/cc @chavafg @jcvenegas A quick peek looks like that was, or has just, done the osbuilder phase. I don't think that normally generates no output for that long though.
I see you are using a `travis_wait` in your script - maybe you could try extending the timeout for one run to see if we really are busy for that long (I think it says you can do that [here](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received). But, we should not generate no output for that long I think.

**Comment by nitkon** [comment]
@grahamwhaley : I extended the `travis_wait` to 50min and the tests completed successfully in approx 30min. Here are the [results](https://travis-ci.org/nitkon/osbuilder/jobs/397394676). Should we extend `travis_wait` to 30-40min?

**Comment by jodh-intel** [comment]
Hi @nitkon - I'm not so sure it completed successfully. Looking at the end of that log:

```
INFO: Skipping test Can create and run euleros image: travis timeout, see: https://github.com/kata-containers/osbuilder/issues/46
/home/travis/.travis/job_stages: line 190:  5524 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait 50 .ci/run.sh" exited with 0.
```

I'm not averse to extending the timeout. But, I wonder if we can specify a different timeout for each arch? The only worry would be if we extend the timeout and don't notice that, say, for some reason the x86_64 build starts taking longer and longer. With the current timeout, we'd get relatively quick notification of that fact, but not if we increase the timeout significantly.

**Comment by nitkon** [comment]
@jodh-intel : The Travis-CI on Power for 3 tests(test_fedora, test_centos, test_alpine) is taking on an average 25min(inferred from repeated runs). Its a 'green' for [travis-CI](https://travis-ci.org/kata-containers/osbuilder/builds/398119396?utm_source=github_status&utm_medium=notification). I am extending the time to 30 for now. Is it high enough to make it arch-specific.

**Comment by jodh-intel** [comment]
wdyt @chavafg?
