### ISSUE TITLE
Can support for Debian/Ubuntu be added?

### ISSUE THREAD

**Issue by ColinIanKing** [kata-containers/osbuilder#141]
It would be really useful if support for Debian and/or Ubuntu (preferably the Bionic LTS) could be added. Is that on the roadmap?

**Comment by jodh-intel** [comment]
Hi @ColinIanKing - thanks for raising. This is actually a dup of #32. We would love to add support for these distros. I'll take a look at doing this next week...

**Comment by jodh-intel** [comment]
Fixed on #144 :smile:
