### ISSUE TITLE
tests: consider if using `chronic` can reduce our logs sizes

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/osbuilder#145]
Over in the tests repo we make [heavy use](https://github.com/kata-containers/tests/blob/master/.ci/setup_env_ubuntu.sh#L21) of `chronic` to reduce our log output *unless* we fail.
There is no use of `chronic` in the osbuilder repo, but we have quite a lot of `yum` and `dnf` activity. That makes the CI logs for this repo quite large afaict.
Consider if adding some info/echo's and `chronic` to the osbuilder repo use of `yum` and `dnf` will:
- reduce the CI log sizes
- but not reduce the usefulness/information/progress reported to the user who is running the builds by hand.

/cc @chavafg @jcvenegas 
I've also marked this as a bitesize/starter issue, as it should not be too difficult to approach, and there is a base reference over in the tests repo of what to do.

**Comment by marcov** [comment]
"Bumping" this, as lately tests logs have become pretty hard to read. 

I may allocate some time for this if no other volunteer shows up :)
