### ISSUE TITLE
Switch from arch(1) to "uname -m"

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#150]
See (multiple) occurrences of `arch` in: 

- https://github.com/kata-containers/osbuilder/blob/master/rootfs-builder/rootfs.sh

See also:

- https://github.com/kata-containers/tests/pull/607

**Comment by jodh-intel** [comment]
... and as part of this change, we can then drop the horrible `arch` hack here:

- https://github.com/kata-containers/osbuilder/blob/master/rootfs-builder/alpine/Dockerfile.in#L10

**Comment by jodh-intel** [comment]
Well, anyone could have jumped in to make this simple fix, but I have now done that on #227 :smile:

**Comment by eadamsintel** [comment]
When will this get merged?  I have some instructions that use OS Builder and would like to remove my notes to manually edit the script file.   I just pulled the repo and this fix is not there yet.

**Comment by jodh-intel** [comment]
@eadamsintel - I've re-run the CI (which is been a little volatile recently). That's all now passing so we simply need one more ack to get this landed...

**Comment by grahamwhaley** [comment]
tis done
