### ISSUE TITLE
Revamp Makefile

### ISSUE THREAD

**Issue by marcov** [kata-containers/osbuilder#157]
I had a look at the Makefile and I see there's margin for improvement:
- for some targets the prerequisites implies a strict ordering, but GNU make does not guarantee any ordering. So running could fail when using `make -j`. E.g.: `image: rootfs image-only`
- targets that do not create a file should be marked as `.PHONY`
- it's redundant to have `*-only` rules, we can use GNU make dependency checking mechanism to ensure we build only what's needed.

I'd like to work on this if that's desirable for you.

**Comment by jodh-intel** [comment]
Thanks @marcov - it's all yours :)
