### ISSUE TITLE
centos builder should download the gpg key via https

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#16]
Rather than keeping the key in the repo, we should probably just download it securely:

- https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7

See:

- https://www.centos.org/keys/

**Comment by jodh-intel** [comment]
This should be a quick fix.

**Comment by egernst** [comment]
@jodh-intel was it a quick fix?

**Comment by jodh-intel** [comment]
@egernst - for me, yes! @Pennyzct very kindly fixed this on #112! :smile:
