### ISSUE TITLE
show summary of image sizes at end of tests

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#162]
It would be useful to see a formatted list of the images and initrds at the end of the test, showing the sizes of each.

**Comment by marcov** [comment]
Currently images size is set to always be 512MB:

https://github.com/kata-containers/osbuilder/blob/93ad0491ef6d3d0b9d20956071b6b39d0a787b4d/Makefile#L13

https://github.com/kata-containers/osbuilder/blob/93ad0491ef6d3d0b9d20956071b6b39d0a787b4d/image-builder/image_builder.sh#L186

**Comment by jodh-intel** [comment]
Hi @marcov - actually, that's just a starting size - note that `create_rootfs_disk()` is called recursively! :-)

See also: #30.

**Comment by marcov** [comment]
@grahamwhaley: how is PSS affected by the rootfs size? Is it because  we cache in memory the guest filesystem?
