### ISSUE TITLE
rework test to create all images in parallel

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#168]
As we add more distros, the test script:

- https://github.com/kata-containers/osbuilder/blob/master/tests/test_images.sh

... ends up taking longer to run.

To avoid constantly having to increase the test timeout in `.travis.yml`, we should restructure the test script so that it:

- Builds all images simultaneously.
- Only then test the image by configuring the runtime and creating a container.

This will involve splitting the `handle_options()` function so that `build_image()` is called multiple times and backgrounded.

Once all the images have been created, the script can then test the images by iterating sequentially through the images and initrds by calling `install_image_create_container()` and `install_initrd_create_container()` respectively.

**Comment by marcov** [comment]
I'd be glad to help you with this :)
It would be nice to find a way to separate logs of each building process, while still keeping the ability to inspect them on CI servers.

**Comment by jodh-intel** [comment]
Hi @marcov - thanks! Yes, I agree - we need to ensure it's still as easy as possible to debug issues ;)

**Comment by marcov** [comment]
I need a clarification: from the logic inside test_images.sh it seems that:
- rootfs with systemd as init <=> generate regular image
- rootfs with kata-agent as init <=> generate a initrd image

Can you confirm? 
I am actually thinking of using `make` to handle parallel builds, and if the previous holds,  I'd just need to run a couple of make commands with:
```
make -j USE_AGENT=yes {list of distro initrds}
make -j USE_AGENT= image {ist of distro images}
```

**Comment by jodh-intel** [comment]
Hi @marcov - yep, you are correct:

- images use systemd and run the agent as a service.
- initrd images only ever run the agent as PID 1.

We could play around with having the agent as PID 1 in an image but -- aside from completeness -- there doesn't seem much point as nobody is crying out for it.

---

Aside: Speaking of "list", it would be useful to have a  `make list-supported-distros` target (which could just run `rootfs-builder/rootfs.sh -h` maybe).

**Comment by jodh-intel** [comment]
Hi @marcov - https://github.com/kata-containers/osbuilder/issues/168#issuecomment-421922610 is about to become old news - see https://github.com/kata-containers/agent/pull/376 :smile:

**Comment by marcov** [comment]
@jodh-intel so, if I get it right, the tests should generate:
-  when `AGENT_INIT=yes`, both rootfs and initrd images 
-  only rootfs images when starting from a regular systemd rootfs

Can you confirm?
