### ISSUE TITLE
Clean up ubuntu/* files headers

### ISSUE THREAD

**Issue by marcov** [kata-containers/osbuilder#171]
Comments in the headers needs to be cleaned up, most of them are redundant or not up to date.

**Comment by Warlord77** [comment]
Hey is this issue still open , I would like to pick this up

**Comment by marcov** [comment]
Thank you @Warlord77 ;-)

**Comment by grahamwhaley** [comment]
Does indeed still look open @Warlord77 - at a minimum, you could check if the request is still valid, and report back here if it is not so we could close the Issue :-)
But, I suspect the comments still need updating - go for it!
Oh, before you raise your first PR though, I would strongly recommend you read our [PR guide](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#pull-requests), at least so you get the PR commit format right so the CIs don't reject them on first attempt :-)

Thanks!
