### ISSUE TITLE
Create a TravisCI config file

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#18]
This repo is configured for TravisCI, but we don't have a `.travis.yml` yet, hence Travis complains :)

**Comment by jodh-intel** [comment]
Hi @jcvenegas - do you think you could you take a look at this some time this week?

**Comment by jodh-intel** [comment]
We need to ensure that as a minimum all the `osbuilder`-supported distros are tested:

- create a rootfs
- create an image file

And eventually, we should add a test to ensure that the Kata runtimes can use the resulting images.

**Comment by jcvenegas** [comment]
working on it.

**Comment by jodh-intel** [comment]
Fixed on #29.
