### ISSUE TITLE
Calculate disk size based on rootfs size

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/osbuilder#2]
In raw images creation, Instead of change the disk size  manually would be better to calculate the disk size.

It is need to find a way to do it:

Some disk space is reserved in ext4
After partition the disk , the available space in the partition is not the same as the full disk (alignment) an other factors make this a bit variable.

**Comment by harche** [comment]
Refer to, https://github.com/kata-containers/osbuilder/pull/30

**Comment by jodh-intel** [comment]
Fixed by #30.
