### ISSUE TITLE
./image_builder.sh get "e2fsck: Cannot continue, aborting" each time in ubuntu

### ISSUE THREAD

**Issue by teawater** [kata-containers/osbuilder#204]
script -fec 'sudo -E USE_DOCKER=true ./image_builder.sh ${ROOTFS_DIR}'
Script started, file is typescript
[sudo] password for teawater:
Sending build context to Docker daemon  536.9MB
Step 1/3 : From fedora:latest
 ---> 8c568f104326
Step 2/3 : RUN [ -n "$http_proxy" ] && sed -i '$ a proxy='$http_proxy /etc/dnf/dnf.conf ; true
 ---> Using cache
 ---> 5c404d9eadc1
Step 3/3 : RUN dnf install -y qemu-img parted gdisk e2fsprogs
 ---> Using cache
 ---> acb3e22760e3
Successfully built acb3e22760e3
Successfully tagged image-builder-osbuilder:latest
[OK] init is installed
[OK] init is systemd
[OK] Agent installed
INFO: Create root disk image. Attempt 1 out of 5.
INFO: Creating raw disk with size 128M
[OK] Image file created
INFO: Creating partitions
[OK] Partitions created
/dev/loop8: gpt partitions 1
INFO: Formatting Image using ext4 filesystem
INFO: Mounting root partition
[OK] Image formatted
INFO: Set filesystem reserved blocks percentage to 3%
[OK] root partition mounted
tune2fs 1.44.3 (10-July-2018)
Setting reserved blocks percentage to 3% (967 blocks)
INFO: Free space root partition  112 MB
INFO: Waiting for /dev/loop8 to detach
INFO: detached
INFO: Create root disk image. Attempt 2 out of 5.
INFO: Image size 128MB too small, trying again with size 256MB
INFO: Creating raw disk with size 256M
[OK] Image file created
INFO: Creating partitions
[OK] Partitions created
/dev/loop8: gpt partitions 1
.INFO: Formatting Image using ext4 filesystem
INFO: Mounting root partition
[OK] Image formatted
INFO: Set filesystem reserved blocks percentage to 3%
[OK] root partition mounted
tune2fs 1.44.3 (10-July-2018)
Setting reserved blocks percentage to 3% (1950 blocks)
INFO: Free space root partition  218 MB
INFO: Waiting for /dev/loop8 to detach
INFO: detached
INFO: Create root disk image. Attempt 3 out of 5.
INFO: Image size 256MB too small, trying again with size 384MB
INFO: Creating raw disk with size 384M
INFO: Creating partitions
[OK] Image file created
[OK] Partitions created
/dev/loop8: gpt partitions 1
INFO: Formatting Image using ext4 filesystem
INFO: Mounting root partition
[OK] Image formatted
INFO: Set filesystem reserved blocks percentage to 3%
[OK] root partition mounted
tune2fs 1.44.3 (10-July-2018)
Setting reserved blocks percentage to 3% (2933 blocks)
INFO: Free space root partition  335 MB
INFO: Waiting for /dev/loop8 to detach
INFO: detached
INFO: Create root disk image. Attempt 4 out of 5.
INFO: Image size 384MB too small, trying again with size 512MB
INFO: Creating raw disk with size 512M
[OK] Image file created
INFO: Creating partitions
[OK] Partitions created
/dev/loop8: gpt partitions 1
INFO: Formatting Image using ext4 filesystem
INFO: Mounting root partition
[OK] Image formatted
INFO: Set filesystem reserved blocks percentage to 3%
[OK] root partition mounted
tune2fs 1.44.3 (10-July-2018)
Setting reserved blocks percentage to 3% (3916 blocks)
INFO: Free space root partition  452 MB
INFO: rootfs size 375 MB
INFO: Copying content from rootfs to root partition
[OK] rootfs copied
e2fsck 1.44.3 (10-July-2018)
e2fsck: Cannot continue, aborting.
/dev/loop8p1 is in use.
Script done, file is typescript

**Comment by marcov** [comment]
That's weird, since we are running CI tests on a ubuntu host.

So e2fsck is erroring out, and the most obvious reason is that the partition specified is still mounted.

Can you run a add a line with 
```
mount | grep loop
```
right before this line: https://github.com/kata-containers/osbuilder/blob/ea8004087af3d3a532eecc0567100283302dd416/image-builder/image_builder.sh#L281

This is to check if there's a problem with unmounting the loop device.

**Comment by teawater** [comment]
@marcov Thanks!
When I tried to add this line, I found that I cannot reproduce this issue.
