### ISSUE TITLE
s390 fedora: need to set the CC variable

### ISSUE THREAD

**Issue by alicefr** [kata-containers/osbuilder#217]
Hi, I'm verifying the various OS for the `initrd` on s390 and for fedora I'm having this issue:
```sh
$ make DISTRO=fedora USE_DOCKER=yes AGENT_INIT=yes
[...]
libsepol.s390x 2.7-6.fc28                                                     
  ncurses-base.noarch 6.1-4.20180224.fc28                                       
  ncurses-libs.s390x 6.1-4.20180224.fc28                                        
  pcre2.s390x 10.31-4.fc28                                                      
  setup.noarch 2.11.3-1.fc28                                                    
  tzdata.noarch 2018d-1.fc28                                                    

Complete!
INFO: Pull Agent source code
[OK] Pull Agent source code
INFO: Build agent
~/go/src/github.com/kata-containers/agent /
rm -f kata-agent kata-agent.service
go build -buildmode=pie -tags "" -o kata-agent \
	-ldflags "-X main.version=1.4.0-07a0832c164ecb8183728c4580117190f87d6300 -X main.seccompSupport=no"
# runtime/cgo
exec: "s390x-linux-gnu-gcc": executable file not found in $PATH
make: *** [Makefile:50: kata-agent] Error 2
Makefile:35: recipe for target '/root/go/src/github.com/kata-containers/osbuilder/.fedora_rootfs.done' failed
make: *** [/root/go/src/github.com/kata-containers/osbuilder/.fedora_rootfs.done] Error 2
```
I've actually found the cause. The CC variable needs to be set to `gcc`:
```sh
$ git diff
diff --git a/rootfs-builder/rootfs.sh b/rootfs-builder/rootfs.sh
index dfedc85..cb0be9c 100755
--- a/rootfs-builder/rootfs.sh
+++ b/rootfs-builder/rootfs.sh
@@ -372,6 +372,7 @@ AGENT_DIR="${ROOTFS_DIR}/usr/bin"
 AGENT_DEST="${AGENT_DIR}/${AGENT_BIN}"
 
 if [ -z "${AGENT_SOURCE_BIN}" ] ; then
+       export CC=gcc
        info "Pull Agent source code"
        go get -d "${GO_AGENT_PKG}" || true
        OK "Pull Agent source code"
$ make DISTRO=fedora USE_DOCKER=yes AGENT_INIT=yes
Creating rootfs for fedora
/root/go/src/github.com/kata-containers/osbuilder/rootfs-builder/rootfs.sh -o 1.4.0-72c5f6a223964e6c3dae220bb6cd08bd94be8c8b-dirty -r /root/go/src/github.com/kata-containers/osbuilder/fedora_rootfs fedora
[...]
[OK] Agent is installed
INFO: Creating /root/go/src/github.com/kata-containers/osbuilder/kata-containers-initrd.img based on rootfs at /root/go/src/github.com/kata-containers/osbuilder/fedora_rootfs
115495 blocks

```
where could be the best place to set the CC variable?

**Comment by jodh-intel** [comment]
Hi @alicefr - that's a good question. It would be safest to set it in `rootfs-builder/rootfs.sh` (`CC=${CC:-gcc}`) as the script can be called without using `make`. But for convenience it might also make sense to set it in the `Makefile` too.

**Comment by marcov** [comment]
@alicefr is the same error being generated also when building the agent with `make` on s390? 
 I am wondering if this is something not correctly handled in Fedora or go.

**Comment by alicefr** [comment]
@marcov no, but it's because I'm working on a `ubuntu`. I can build the ubuntu/alpine/debian initrd without problems. The issue is only for fedora

**Comment by alicefr** [comment]
I think, I add the possibility to set the CC (not as defaul) and we can set the variable in the case of fedora on s390x

**Comment by marcov** [comment]
> @marcov no, but it's because I'm working on a ubuntu. I can build the ubuntu/alpine/debian initrd without any problems.

@alicefr thanks for reporting.  Maybe you could try with a Fedora container ;)

fyi gcc is being called by go to link the agent binary in PIE mode. 
To me it looks like Fedora does not provide the correct gcc binary to go. 
It could just be the lack of a package though. If not, this could be something worth reporting to Fedora.

> I think, I'll set the docker_extra args in the case s390 and fedora. It' the less invasive possibility

I think that's right as a solution.

**Comment by alicefr** [comment]
@marcov I'm building using docker. I checked on another fedora system that I have for s390. There, CC for go is set to `gcc`. i don't why it's the wrong set up

**Comment by marcov** [comment]
Ok I see, so let's just fix this for kata.

**Comment by alicefr** [comment]
I double checked it happens when you directly download and install go from the download page. If I install golang directly from fedora package mangare the CC variable is correctly set. I need to fix the case also if the initrd is directly built on a fedora s390

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
oops! ;)
