### ISSUE TITLE
latest clearlinux version makes yum fail inside a container  

### ISSUE THREAD

**Issue by chavafg** [kata-containers/osbuilder#237]
Kata containers image using Clearlinux version 28190 (and probably above) makes a Centos container to fail when running `yum -y update.`.

Related: https://github.com/kata-containers/tests/issues/1270 

The issue happens when using image kata-containers-clearlinux-28190-osbuilder-da9f541-agent-a2037c0.img.tar.xz. I ran the yum update inside the centos container and at the same time I ran top. I see that the yum process uses 99% of the CPU and stays there while it is running. 

When downgrading to image kata-containers-clearlinux-28100-osbuilder-da9f541-agent-a2037c0.img.tar.xz, this issue does not happen. The yum update inside the container finishes correctly and the CPU usage of the container does not get above 60% and the command finishes successfully.

**Comment by devimc** [comment]
Seems like this is a problem with systemd 241, systemd 239 works for me.

... and here we are, with systemd biting us, I told y'all (https://github.com/kata-containers/runtime/pull/768) :nerd_face:

**Comment by jodh-intel** [comment]
Do we have details on how systemd could be affecting `yum` yet?

**Comment by ahkok** [comment]
> Seems like this is a problem with systemd 241, systemd 239 works for me.

How did you establish this?

**Comment by ahkok** [comment]
> I ran the yum update inside the centos container and at the same time I ran top. I see that the yum process uses 99% of the CPU and stays there while it is running.

Can we do a little bit more exploratory debugging into this? `top` isn't exactly very detailed. An `strace -f -p <pid)` would already show a lot more information.

**Comment by grahamwhaley** [comment]
I thought this issue had been solved, but maybe not - seen over in https://github.com/kata-containers/runtime/issues/1916
@bryteise - is this something you can assess and chase if need be?
