### ISSUE TITLE
Allow distro-specific IMG_SIZE to be specified in config.sh

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#24]
We should allow `IMG_SIZE=` to be specified in `config.sh` and use the `Makefile` to pass that value to `image_builder.sh -s`.

That will partly solve the issue of different distros needing different image sizes. However, if the user specifies `EXTRA_PKGS=`, the `IMG_SIZE=` value will likely be too low.

**Comment by devimc** [comment]
`IMG_SIZE` is no more supported, rootfs image is as small as possible
