### ISSUE TITLE
rootfs: DAX: use ndctl to fill out the device namespace information 

### ISSUE THREAD

**Issue by devimc** [kata-containers/osbuilder#240]
once `ndctl` has support for namespace information in raw files, we should use it to setup the rootfs image instead of `image-builder/nsdax.gpl.c`

**Comment by sboeuf** [comment]
@devimc 
Just to clarify, what do you mean by using it inside? Is this something that would run when creating the rootfs (like the patch that you added with `image-builder/nsdax.gpl.c`), or would this be something running when the VM is booted every time?

**Comment by devimc** [comment]
@sboeuf oops, sorry, description updated

*we should use ndctl to setup the rootfs image instead of image-builder/nsdax.gpl.c*
