### ISSUE TITLE
dax fix makes osbuilder images unbootable

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#245]
Cannot boot osbuilder-created image:

From `proxy.log`:

```
[    0.325375] VFS: Cannot open root device \"pmem0p1\" or unknown-block(0,0): error -6
[    0.325480] Please append a correct \"root=\" boot option; here are the available partitions:
[    0.326949] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
```

Reverting https://github.com/kata-containers/osbuilder/pull/236 locally fixes the problem for me.

**Comment by devimc** [comment]
@jodh-intel thanks for raising this, but seem like you need to build you own guest kernel with the latest configuration, feel free to reopen it if I'm wrong.

**Comment by sboeuf** [comment]
Yes you need latest config and make sure you're not running 4.14 kernel, otherwise this won't work.

**Comment by jodh-intel** [comment]
Thanks @devimc. For reference, I was testing with qemu and the latest packaged kernel (version `4.19.24.25-20`), but that kernel doesn't include `CONFIG_ZONE_DEVICE=y` (from https://github.com/kata-containers/packaging/pull/385).

I guess theoretically if we adopted https://github.com/kata-containers/packaging/issues/226, we *could* add a check to `kata-check` which would then be able to determine if the zone config settings are enabled and could also probe the configured image (#236).
