### ISSUE TITLE
Add an "auto-size" feature

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#25]
Add an option to allow the minimum size of the rootfs to be determined automatically.

Strategy:

- Start with an initial `IMG_SIZE=` value (make it purposely large - `200M`?)
- Attempt to build an image.
- If the image is built successfully, half the size and repeat.
- If the image is not built successfully increase the size by half of the size it was reduced by and repeat.

That option will be useful to allow inbuilt-defaults to be set (#24), but it would also be useful if a user wishes to build an image with additional package (`EXTRA_PKGS=`) since then the scripts cannot determine in advance the smallest image possible for that distro + package combination.

**Comment by harche** [comment]
It doesn't have to start with `IMAGE_SIZE=`. IMHO, it should start with `ROOTFS_SIZE=` and add maybe about 20% to create the raw image. If it's not sufficient, rinse and repeat.

**Comment by jodh-intel** [comment]
@harche - agreed :smile:

**Comment by harche** [comment]
I will work on PR for this.

**Comment by jodh-intel** [comment]
Thanks @harche !

**Comment by grahamwhaley** [comment]
I think previously maybe @jcvenegas had considered doing a first run with a very large SIZE, then looking at how much size was actually needed, and then doing a second run with the correct minimal size.... so, just 'two iterations' hopefully?

Also, I've not looked at the details - but is this a filesystem that maybe can be 'resized' after it is generated - which could save us an actual build cycle, and we could do:

- build
- measure
- resize

? (just thinking aloud...)

**Comment by jodh-intel** [comment]
This gets better and better ;)

**Comment by jcvenegas** [comment]
@jodh-intel  @harche @grahamwhaley , It was the first idea to try to reduce by checking the size need in the partition. Having extra disk space a good point to consider, we need to know if kata agent require some need storage or if all it is created on tmpfs ?.

But as starting point is good to have just the auto-size feature.
