### ISSUE TITLE
Add chrony service to rootfs

### ISSUE THREAD

**Issue by amshinde** [kata-containers/osbuilder#255]
As per https://github.com/kata-containers/runtime/issues/1279, we need to package chrony to sync guest clock with host. kvm_ptp is already enabled in our guest. chrony needs to be configured with ptp as source.

**Comment by devimc** [comment]
> chrony needs to be configured with ptp as source

so that mean clone it and build it manually?, or should we rely on distro's version?

can we use the `SetGuestDateTime` API instead of chrony ?

**Comment by WeiZhang555** [comment]
I think `SetGuestDateTime` will never get an accurate time, GRPC communication cost times too, so if you get the host time then pass it to agent with `SetGuestDateTime` , the time is outdated when it reaches.
