### ISSUE TITLE
Is it possible that Kata osbuilder supports Windows server?

### ISSUE THREAD

**Issue by jamesxia20181001** [kata-containers/osbuilder#262]
Is it possible that Kata osbuilder supports Windows server?
For example : Linux based container OS+kata support linux containers and windows server contaniers at the same time on a single node.

**Comment by grahamwhaley** [comment]
Hi @jamesxia20181001 - so, to be able to run a Windows container on a Linux host...
I've been asked the question a few times, and I thought I'd writting a reply to a previous Issue, but cannot locate it...
To run a Windows container you would need I believe a Windows VM/'kernel'/rootfs (that is, you would need to run a Windows VM to container the Windows Container). AFAIK, the key missing element here will be having a Windows 'agent'(https://github.com/kata-containers/agent). So far nobody has stepped forwards to port/write that for Windows.

To understand more of why you need this, the [architecture documentation](https://github.com/kata-containers/documentation/blob/master/architecture.md) may help. You basically need something (the agent) inside the Windows VM to be able to construct, constrain and manage the container, whilst talking back to the host.
