### ISSUE TITLE
Error while building osbuilder on SLES

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/osbuilder#270]
While running osbuilder on SLES 12 SP3, I am getting the following error
```
14:22:25 Successfully built 2c867e8f88aa
14:22:25 Successfully tagged image-builder-osbuilder:latest
14:22:26 [OK] init is installed
14:22:26 [OK] init is systemd
14:22:26 mount: /tmp/tmp.gdFlTY0MCs: wrong fs type, bad option, bad superblock on /dev/loop0p1, missing codepage or helper program, or other error.
14:22:26 umount: /tmp/tmp.gdFlTY0MCs: not mounted.
14:22:26 /osbuilder/image_builder.sh: line 203: [: 22G: integer expression expected
14:22:27 mount: /tmp/tmp.gdFlTY0MCs: wrong fs type, bad option, bad superblock on /dev/loop0p1, missing codepage or helper program, or other error.
14:22:27 umount: /tmp/tmp.gdFlTY0MCs: not mounted.
14:22:27 /osbuilder/image_builder.sh: line 203: [: 22G: integer expression expected
14:22:27 mount: /tmp/tmp.gdFlTY0MCs: wrong fs type, bad option, bad superblock on /dev/loop0p1, missing codepage or helper program, or other error.
14:22:27 umount: /tmp/tmp.gdFlTY0MCs: not mounted.
14:22:27 /osbuilder/image_builder.sh: line 203: [: 22G: integer expression expected
14:22:27 mount: /tmp/tmp.gdFlTY0MCs: wrong fs type, bad option, bad superblock on /dev/loop0p1, missing codepage or helper program, or other error.
14:22:27 umount: /tmp/tmp.gdFlTY0MCs: not mounted.
```
Here it is the complete debug console 
http://jenkins.katacontainers.io/job/kata-containers-tests-sles-12-master/3/

/cc @devimc and @jcvenegas

**Comment by devimc** [comment]
The problem is host kernel

```
EXT4-fs (loop9p1): Couldn't mount RDWR because of SUSE-unsupported optional feature METADATA_CSUM.  Load module with allow_unsupported=1.
```

the image should be generated without the `USE_DOCKER` env var

**Comment by devimc** [comment]
cc @marcov

**Comment by devimc** [comment]
we can workaround this issue by downgrading the version of the fedora container that is used to generate the image, https://github.com/kata-containers/osbuilder/blob/master/image-builder/Dockerfile#L6 , `fedora:27` works fine

**Comment by GabyCT** [comment]
wdyt? @jcvenegas and @jodh-intel

**Comment by devimc** [comment]
Workaround 2

Don't modify fedora version (`latest` is fine) and remove `metadata_csum` from the image with the following command: `tune2fs -O ^metadata_csum ....`

**Comment by jcvenegas** [comment]
So it is a host kernel issue not a lot of options there.
If that does not bring any additional issue. `Workaround 2` is a good solution nice finding @devimc. We can  give a cycle on the CI and see how it goes.

**Comment by devimc** [comment]
please take a look https://github.com/kata-containers/osbuilder/pull/272
