### ISSUE TITLE
OS_VERSION variable is not being respected

### ISSUE THREAD

**Issue by eadamsintel** [kata-containers/osbuilder#274]
I am running the following with OS builder.  It respects the EXTRA_PKGS variable but it ignores the OS_VERSION variable and always uses the default.

```
mkdir -p $OSBUILDER
cd $OSBUILDER
git clone https://github.com/kata-containers/osbuilder.git
export ROOTFS_DIR=${OSBUILDER}/osbuilder/rootfs-builder/rootfs
export OS_VERSION='27700' 
export EXTRA_PKGS='kmod'
cd ${OSBUILDER}/osbuilder/rootfs-builder
sudo rm -rf ${ROOTFS_DIR}
script -fec 'sudo -E GOPATH=$GOPATH USE_DOCKER=true SECCOMP=no ./rootfs.sh clearlinux'
```

This is what ends up happening

```
Unable to detect release version (use '--releasever' to specify release version)
Clear-28670 clear                               3.2 MB/s |  10 MB     00:03
```
  
This also failed.  

`sudo -E GOPATH=$GOPATH USE_DOCKER=true OS_VERSION=27700 SECCOMP=no ./rootfs.sh clearlinux`

**Comment by marcov** [comment]
hi @eadamsintel, thank you for reporting this!

Indeed, when building with Docker, the `OS_VERSION` env is not passed in the container. This is something to fix.

Without Docker however it should work. I did some tests and the `OS_VERSION` value is respected. Can you please double check?
The message:
```
Unable to detect release version (use '--releasever' to specify release version)
``` 
seems to always be generate by `yum` irrespectively of the `OS_VERSION` provided.

**Comment by jodh-intel** [comment]
@marcov, @jcvenegas - we keep having this issue where we forget to add `--env foo=bar` to the `docker run` invocation. So, how about we do something like this:

- Mandate that all variables the script uses start with `OSBUILDER_`
 
  In other words rename `ROOTFS_DIR` to `OSBUILDER_ROOTFS_DIR`, *etc*.

  Yes, that might break some people, but it's a one-off change.

- Update `rootfs.sh` to run:

  ```sh
  docker run --env-file <(env | egrep "OSBUILDER_|_proxy") ...
  ```

  That way, we're much less likely to forget as that will auto-set all the variables we care about.?

**Comment by marcov** [comment]
@jodh-intel that's a good idea.

Wondering what may break/required changes to this:
- documentation (Developer Guide)
- OBS packages

During the transition we could add something that detects envs with the "old" name and throws a warning/error message.

**Comment by jcvenegas** [comment]
@jodh-intel that is a sane approach I recently had some issues using azure pipelines because they use the variable AGENT_VERSION.

 agree with @marcov  we could try to do a grep over all repos to reduce the impact of the change and need to sync to try to do it at the same time.

**Comment by jodh-intel** [comment]
If someone wants to pick this up, I've raised the following listing what I think needs to change "atomically" ;)

- https://github.com/kata-containers/kata-containers/issues/43
