### ISSUE TITLE
Add new seccomp requirements

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#28]
Once a PR that fixes https://github.com/kata-containers/agent/issues/104 lands, we'll need to update the Rootfs requirements in `rootfs-builder/README.md` to include `libseccomp`.

**Comment by nitkon** [comment]
@jodh-intel : So whats the latest on seccomp support in Kata Containers?

**Comment by jodh-intel** [comment]
@nitkon - we're still waiting for someone to pick up the issue above... :)

**Comment by egernst** [comment]
stale. @nitkon @jodh-intel  - anything new here?

**Comment by jodh-intel** [comment]
Could you tal @nitkon?
