### ISSUE TITLE
dmesg test failing on the CI

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/osbuilder#302]
The following test is failing 
```
13:13:39 [1] • Failure [13.651 seconds]
13:13:39 [1] check dmesg logs errors
13:13:39 [1] /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:277
13:13:39 [1]   Run to check dmesg log errors
13:13:39 [1]   /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:294
13:13:39 [1]     should be empty [It]
13:13:39 [1]     /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:295
13:13:39 [1] 
13:13:39 [1]     Expected
13:13:39 [1]         <string>: [    0.619595] systemd[72]: tmp.mount: Failed to execute command: No such file or directory
13:13:39 [1]         [    0.619844] systemd[72]: tmp.mount: Failed at step EXEC spawning /usr/bin/mount: No such file or directory
13:13:39 [1]     to be empty
13:13:39 [1] 
13:13:39 [1]     /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:305
13:13:39 [1] ------------------------------
13:13:39 [1] 
```
/cc @amshinde

**Comment by amshinde** [comment]
@chavafg @GabyCT I guess this is in the clearlinux rootfs. I had tested this for centos rootfs, just because I find it easier to setup a debug console with it.
Looks like mount command is missing in clearlinux. I'll try to reproduce this issue first.

**Comment by amshinde** [comment]
Set up a debug console for clearlinux. Thid is what the /usr/bin looks like:
```
/usr/bin/
arptables                       loginctl
arptables-nft                   machinectl
arptables-nft-restore           mkhomedir_helper
arptables-nft-save              networkctl
arptables-restore               nfnl_osf
arptables-save                  pam_tally
bash                            pam_tally2
bootctl                         pam_timestamp_check
busctl                          portablectl
chronyc                         poweroff
chronyd                         reboot
coredumpctl                     resolvconf
ebtables                        resolvectl
ebtables-nft                    runlevel
ebtables-nft-restore            sh
ebtables-nft-save               shutdown
ebtables-restore                systemctl
ebtables-save                   systemd-analyze
halt                            systemd-ask-password
hostnamectl                     systemd-cat
init                            systemd-cgls
ip6tables                       systemd-cgtop
ip6tables-legacy                systemd-delta
ip6tables-legacy-restore        systemd-detect-virt
ip6tables-legacy-save           systemd-escape
ip6tables-nft                   systemd-id128
ip6tables-nft-restore           systemd-inhibit
ip6tables-nft-save              systemd-machine-id-setup
ip6tables-restore               systemd-mount
ip6tables-restore-translate     systemd-notify
ip6tables-save                  systemd-nspawn
ip6tables-translate             systemd-path
iptables                        systemd-resolve
iptables-legacy                 systemd-run
iptables-legacy-restore         systemd-socket-activate
iptables-legacy-save            systemd-stdio-bridge
iptables-nft                    systemd-tmpfiles
iptables-nft-restore            systemd-tty-ask-password-agent
iptables-nft-save               systemd-umount
iptables-restore                telinit
iptables-restore-translate      timedatectl
iptables-save                   udevadm
iptables-translate              unix_chkpwd
iptables-xml                    unix_update
journalctl                      xtables-legacy-multi
kata-agent                      xtables-monitor
ldconfig                        xtables-nft-multi
localectl                       
```
The `mount` command is missing. So are commands like `ls`, `cat`.
I could not run a `ls` or `systemctl cat tmp.mount` at all.
(As the tmp.mount unit is autostarted, looks like the systemd dependencies are different in a `clearlinux` and `centos` mini-os, and those are the two that I ended up testing so far)

cc @jcvenegas

**Comment by amshinde** [comment]
Looks like `util-linux-bin` (which contains the `mount` command among others) is not being pulled as a dependency for systemd in Clearlinux.  The  `util-linux-bin` package is listed as a dependency for systemd all other distros. This seems to be a clear nuance :)
I am going to add this package explicitly for Clear in os-builder to fix this issue. (This would add another 3204K to the image size)

I also noticed that `coreutils-bin` is not being pulled either(this should be a dependency for libc6 which should be pulled in by systemd). This explains the absence of commands such as `ls`, `cat` in the clearlinux rootfs.
Though I dont see this breaking anything today, we should probably be adding this as well.
If not atleast list this as a requirement for debug shell for clearlinux. Without `coreutils`, the debug shell is pretty useless for Clear.
Thoughts @grahamwhaley @jodh-intel ?

**Comment by jodh-intel** [comment]
I wonder if using `busybox` would suffice as that provides `ls`, `cat`, and `mount`?

That said, although it appears to be packaged for Clear, it has not been updated for a long time:

- https://github.com/clearlinux-pkgs/busybox/blob/master/busybox.spec

/cc @devimc who might have a view on increasiing image size :smile:

**Comment by grahamwhaley** [comment]
Maybe we should also consider attack surface as well as just footprint - if we don't need these tools in the mini-os to launch container workloads, then we should probably not include them in our base image. Yes, that might mean if somebody wants to get a *useful* debug console enabled then they will also have to build/use a fuller rootfs image to get some of the utils - but, our primary use case of the mini-os is to run containers. Debug console is a dev corner case, and (hopefully) not the norm.

**Comment by grahamwhaley** [comment]
Reading back up the issue - I presume that systemd `mount` fail is a real symptom of a real issue? Do we know what it failed to mount? I'm slightly confused - did the upstream Clear Linux change its packaging, which dropped `mount` for us, and thus has now started to fail our CI checks (nice check btw heh ;-) )

**Comment by jodh-intel** [comment]
I know we've discussed this sort of issue *ad nauseam* a few times before guys. Adding `coreutils` and `util-linux` is going to add ~200 commands. A "full" busybox install would add more (my Fedora `busybox` provides 388 commands), but `busybox` could of course be configured to simply add the individual commands.

Another alternative would be to build with `coreutils` and `util-linux` but delete everything not needed by `mount`, `ls`, blah.

**Comment by grahamwhaley** [comment]
@jodh-intel - looking at that Clear Linux `busybox` package repo, does that imply that there is just a small subset of commands enable/built in that busybox (including `mount`)?
@bryteise - what's the deal with the CLR busybox package - I guess they don't auto update versions? Does that package have an owner who could bump/maintain/track the upstream?

**Comment by jodh-intel** [comment]
@grahamwhaley - Looks that way to me. And that's why I was suggesting `busybox` as an alternative to the other two packages. We'd only need to add `cat` potentially if @amshinde thinks we need that. I believe that coreutils has grown similar multi-call binary abilities but I haven't looked at it. We can't use `busybox` from CLR if it isn't being updated though.

**Comment by bryteise** [comment]
@grahamwhaley We don't build busybox any more.
