### ISSUE TITLE
 auto-generating the dockerfile

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/osbuilder#31]
USE_DOCKER=true variable allows to build images and rootfs using docker. To do that sometimes is required to use a Dockerfile with the packages needed to create a job.

Because there are different Dockerfiles and they use a specific  dockerhub distro version, add a way to define all those versions in a file (versions.txt) to easily update when required.

**Comment by jodh-intel** [comment]
See: https://github.com/kata-containers/osbuilder/pull/29#pullrequestreview-90176803.

**Comment by jodh-intel** [comment]
Fixed by #40.
