### ISSUE TITLE
Is it better to configure chronyc service with makestep options

### ISSUE THREAD

**Issue by xs3c** [kata-containers/osbuilder#316]
# Description of problem

man chronyc
 
> makestep, makestep threshold limit
          Normally chronyd will cause the system to gradually correct any time offset, by slowing down or speeding up the clock as
          required. In certain situations, the system clock might be so far adrift that this slewing process would take a very
           long time to correct the system clock.
         The makestep command can be used in this situation. There are two forms of the command. The first form has no
          parameters. It tells chronyd to cancel any remaining correction that was being slewed and jump the system clock by the
          equivalent amount, making it correct immediately.
           The second form configures the automatic stepping, similarly to the makestep directive. It has two parameters, stepping
           threshold (in seconds) and number of future clock updates for which the threshold will be active. This can be used with
           the burst command to quickly make a new measurement and correct the clock by stepping if needed, without waiting for
           chronyd to complete the measurement and update the clock.

# Expected result

the system time is corrected asap.

# Actual result

the system time is not corrected asap

**Comment by devimc** [comment]
cc @amshinde
