### ISSUE TITLE
Add support for Ubuntu

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#32]
We should add the ability to create an Ubuntu rootfs by creating the required set of config files below:

- https://github.com/kata-containers/osbuilder/tree/master/rootfs-builder

**Comment by ydjainopensource** [comment]
@jodh-intel I have a WIP PR.  
I have used debootstrap but it needs chroot privileges...Is there another way of doing this without running a privileged container?

**Comment by jodh-intel** [comment]
Let's block on #39 which will simplify adding Ubuntu support.
