### ISSUE TITLE
Add support for SuSE

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#33]
We should add the ability to create a SuSE-based rootfs by creating the required set of config files below:

- https://github.com/kata-containers/osbuilder/tree/master/rootfs-builder

**Comment by jodh-intel** [comment]
Let's block on #39 which will simplify adding SuSE support.

**Comment by marcov** [comment]
I'd like to work on this!

**Comment by jodh-intel** [comment]
Hi @marcov - thanks! It's all yours! :smile:

Unfortunately, I cannot assign it to you (github doesn't seem to allow it), but I'll add it in my name so it's clear that "someone" is working on it (you! :)

**Comment by grahamwhaley** [comment]
yeah, you can only assign to members of the github org. We should discuss how one becomes a member, as afaik we don't have that defined - let me open an issue and consult with the oracles...

**Comment by jodh-intel** [comment]
/me tries to waft the incense-laden smoke out of his eyes whilst @grahamwhaley get's to it...
