### ISSUE TITLE
fix service start fail issue for arm64

### ISSUE THREAD

**Issue by jongwu** [kata-containers/osbuilder#347]
# Description of problem

now, some systemd services will fail to start if PrivateTmp in systemd config is set to true, as mount private directory under /var/tmp will fail if /var/tmp linked to /tmp.

# Expected result

systemd service enable PrivateTmp will start.

# Actual result

systemd service enable PrivateTmp will fail

**Comment by devimc** [comment]
closing issue, this will be fixed here https://github.com/kata-containers/osbuilder/pull/350
