### ISSUE TITLE
Make sure (dracut) initrd modules are loaded before kata agent service

### ISSUE THREAD

**Issue by marcov** [kata-containers/osbuilder#353]
When building an initrd using the dracut method, the user has the ability to specify a set of kernel modules to load using systemd.

However, we should guarantee that these modules are loaded *before* the kata agent service is started.

**Comment by crobinso** [comment]
This came from a discussion here: http://lists.katacontainers.io/pipermail/kata-dev/2019-September/000993.html

I have a patch attached to that thread which added a kata-agent dep on systemd-udev-settle, which is one solution. Another could be to have kata-agent depend on systemd-modules-load. Either of those pieces may slow down kata-agent startup in other scenarios though, like with a kernel without modules? I'm not really sure.

**Comment by marcov** [comment]
Thank you @crobinso. 

Depending on systemd-udev-settle seems to be the most conservative choice, but as you said it may slow down things. On the other side, this may well be required both for modular and monolithic kernels.

Another choice would be to have the kata-agent sit there and wait  for all the necessary HW to be available.

Calling in @devimc who is knowledgeable about the agent internals.

**Comment by devimc** [comment]
I added support for loading kernel modules using the `kata-agent` without depending on systemd (initrd case),  see https://github.com/kata-containers/runtime/blob/master/cli/config/configuration-qemu.toml.in#L353 , If this solution works for you I can add another patch to make them configurable at build time

**Comment by devimc** [comment]
btw I'm working on the documentation :sweat_smile:

**Comment by crobinso** [comment]
I think on the Fedora side for the short/medium term I will stick with using systemd init while we try to get something working with only distro packages; systemd is a more know quantity and will be easier for me to introspect/debug if things go wrong. Exploring kata-agent as init is interesting for later though

**Comment by marcov** [comment]
Thank you @devimc, that's something really needed. 

Your solutions goes in the same direction of what was stated here by @egernst: http://lists.katacontainers.io/pipermail/kata-dev/2019-September/001011.html , i.e. having kata-agent as init to optimize boot time and resources usage.

WDYT about also having a config inside the guest image that kata-agent reads?
This would cover different use cases:
- at image build time, you specify a list of modules that must be loaded all the times to have a minimal host-to-guest interaction (e.g., 9p or virtio-net).
- at run time, you can specify extra modules that are specific to the kind of workloads run.

The motivation is that, when I am building an image, I am pairing it with a specific kernel version, and I know that this kernel requires specific modules to be loaded as start up.

**Comment by jodh-intel** [comment]
Agreed. We already have such a config file of course in the form of `/var/lib/osbuilder/osbuilder.yaml`:

- https://github.com/kata-containers/osbuilder/blob/83b89d8773addac4b42104386df29b740af35d63/scripts/lib.sh#L161
