### ISSUE TITLE
create a guest OS image error:File /dev/loop12p1 is not a block device

### ISSUE THREAD

**Issue by sunyz-ics** [kata-containers/osbuilder#362]
When I create a guest OS image, the error message is  as follows
`[root@localhost image-builder]# script -fec 'sudo -E  ./image_builder.sh ${ROOTFS_DIR}'
Script started, file is typescript
[OK] init is installed
[OK] init is systemd
losetup: /tmp/tmp.Mscslvwoj3: warning: file smaller than 512 bytes, the loop device maybe be useless or invisible for system tools.
ERROR: File /dev/loop12p1 is not a block device
losetup: /tmp/tmp.Mscslvwoj3: warning: file smaller than 512 bytes, the loop device maybe be useless or invisible for system tools.
ERROR: File /dev/loop13p1 is not a block device
losetup: /tmp/tmp.Mscslvwoj3: warning: file smaller than 512 bytes, the loop device maybe be useless or invisible for system tools.`
I found out because the **qemu-img** package was missing. it would be great if we could  check the qemu-img  before the error message.Hope this information is useful.

**Comment by jodh-intel** [comment]
Hi @sunyz-ics - This sounds odd. The `image-build.sh` script is hard-coded to run with `set -e`, so when `create_disk()` ran, it should have failed on the `qemu-img` call. Unless you have a script called `qemu-img` maybe?

**Comment by sunyz-ics** [comment]
Hi @jodh-intel -I don't know why, I don't have a qemu-img script, I use cenos-7-x86_64-minimal -1810, and when I install qemu-img-1.5.3-160.el7_6.3.x86_64, the  build is successful.
