### ISSUE TITLE
Might need to split run.sh

### ISSUE THREAD

**Issue by yyyeerbo** [kata-containers/osbuilder#367]
travis job is 50m. We run all the distros' test, travis times out. 

We may have to split distros into 2+ parts to run separately.

**Comment by yyyeerbo** [comment]
Ah, I apparently misunderstood the concept of job..
maybe we should run a few distro(clearlinux,ubuntu, alpine) instead of all the distros?

**Comment by jodh-intel** [comment]
We have hit timeouts before and @marcov reworked the scripts to run each distros rootfs + image creation in parallel. I wonder how easy it would be to add the time to build each distro to the summary we produce at the end of each job:

```
INFO: Image and rootfs sizes (in bytes and MB), smallest image first:

 image-bytes	  image-MB	rootfs-bytes	 rootfs-MB	Type    	Name                
    12693920	     12.10	    34100205	     32.52	initrd  	alpine              
   134217728	    128.00	    90250142	     86.06	image   	clearlinux          
   268435456	    256.00	   121876556	    116.23	image   	ubuntu              
   268435456	    256.00	   141662798	    135.10	image   	debian              
   268435456	    256.00	   178849302	    170.56	image   	suse                
   402653184	    384.00	   284268998	    271.10	image   	fedora              
   536870912	    512.00	   353034810	    336.68	image   	centos              
INFO: Detecting agent go version
```
