### ISSUE TITLE
travis:  No match for argument: systemd

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/osbuilder#38]
Travis  tests are  failing  giving the following error
```
# Successfully tagged fedora-rootfs-osbuilder:latest
# INFO: Using : dnf to pull packages from http://mirror.math.princeton.edu/pub/fedora/linux/releases/27/Everything/x86_64/os/
# Unable to detect release version (use '--releasever' to specify release version)
# Failed to synchronize cache for repo 'kata', disabling.
# No match for argument: systemd
```

**Comment by jodh-intel** [comment]
This might be a repo issue as I saw odd errors earlier (but not that one).

Hopefully, #22 will resolve this sort of thing.

**Comment by jcvenegas** [comment]
@jodh-intel  indeed the repository used at the moment is down, by merging #22 and change it to use OS_VERSION  this may be fixed .
