### ISSUE TITLE
make dracut rootfs failed due to invalid option `--directory` be passed to `cpio`

### ISSUE THREAD

**Issue by shiloong** [kata-containers/osbuilder#384]
# Description of problem
Failed to create rootfs by cmd `sudo -E PATH=$PATH make BUILD_METHOD=dracut rootfs`, and `cpio` reported unrecognized option `--directory`.

# Expected result

Can create rootfs by dracut success w/o any error.

# Actual result

failed with following error:
```text
[snipped]
mkdir -p dracut_rootfs
cat /root/workplace/osbuilder/kata-containers-initrd.img | cpio --extract --preserve-modification-time --make-directories --directory=dracut_rootfs
cpio: unrecognized option '--directory=dracut_rootfs'
Try `cpio --help' or `cpio --usage' for more information.
```

It's seems that `cpio` in Linux does not supports option `--directory` any more. Maybe we can change to following:
```diff
diff --git a/Makefile b/Makefile
index d9bdda0..53c920a 100644
--- a/Makefile
+++ b/Makefile
@@ -93,7 +93,7 @@ $(ROOTFS_BUILD_DEST)/.%$(ROOTFS_MARKER_SUFFIX):: rootfs-builder/%
 .PRECIOUS: $(ROOTFS_BUILD_DEST)/.dracut$(ROOTFS_MARKER_SUFFIX)
 $(ROOTFS_BUILD_DEST)/.dracut$(ROOTFS_MARKER_SUFFIX): $(TARGET_INITRD)
        mkdir -p $(TARGET_ROOTFS)
-       cat $< | cpio --extract --preserve-modification-time --make-directories --directory=$(TARGET_ROOTFS)
+       cd $(TARGET_ROOTFS); cat $< | cpio --extract --preserve-modification-time --make-directories
        @touch $@

 image-%: $(IMAGES_BUILD_DEST)/kata-containers-image-%.img
```

This change can create rootfs success in my local ENV, just FYI.

**Comment by grahamwhaley** [comment]
@jcvenegas - can you loop in the other distro/dracut folks - would that be @crobinso for instance?

**Comment by crobinso** [comment]
> It's seems that `cpio` in Linux does not supports option `--directory` any more. Maybe we can change to following:

Hmm, I still see it in https://git.savannah.gnu.org/cgit/cpio.git so that doesn't sound accurate. Maybe busybox cpio or another implementation doesn't support --directory?

Either way, change makes sense to me, but won't using `cd` first change CWD for the following `touch` command? So maybe this should use something akin to pushd/popd, but I'm not sure what the optimal Makefile pattern is for that

CCing @c3d for testing on the Fedora side if that is desired

**Comment by jcvenegas** [comment]
@shiloong the change is OK to try to maximize compatibility as @crobinso point seems that there flag is still there could you confirm what version/implementation your  system is using?

About the pushd popd patter in Makefiles I feel if the target is short just cd is fine as after the target finish the `cd` effect is reverted. 


\cc @flavio

**Comment by shiloong** [comment]
@jcvenegas @crobinso 
My system is **Aliyun Linux 2**, which is fully compatible with CentOS 7.
The `cpio` command I used is:
```
[root@builder ~]# cpio --version
cpio (GNU cpio) 2.11
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Phil Nelson, David MacKenzie, John Oleynick,
and Sergey Poznyakoff.

[root@builder ~]# cpio --directory
cpio: unrecognized option '--directory'
Try `cpio --help' or `cpio --usage' for more information.
```
FYI.

**Comment by c3d** [comment]
> Either way, change makes sense to me, but won't using `cd` first change CWD for the following `touch` command? So maybe this should use something akin to pushd/popd, but I'm not sure what the optimal Makefile pattern is for that

For a single-line case like this, you can also use `(cd ...; cat ... )`

**Comment by flavio** [comment]
@jcvenegas: adding @rhafer, he's now taking care of kata at SUSE

**Comment by rhafer** [comment]
> > It's seems that `cpio` in Linux does not supports option `--directory` any more. Maybe we can change to following:
> 
> Hmm, I still see it in https://git.savannah.gnu.org/cgit/cpio.git so that doesn't sound accurate. Maybe busybox cpio or another implementation doesn't support --directory?

Actually, `--directory` got added with a somewhat recent versions (2.12) IIUC, So it might not be present the older distros yet (seems that e.g. SLE12 and CentOS 7 still ship 2.11). If there is really  the need to support these release (Leap/SLE15 and CentOS8 should already ship at least 2.12) I guess that `(cd ...; cat ... )` thing is fine

**Comment by jcvenegas** [comment]
@shiloong you want to take this issue ?

**Comment by shiloong** [comment]
> @shiloong you want to take this issue ?

So `(cd ...; cat ...)` is OK to fix this issue, right?
It's OK for me to take it. I'll send pull request soon.

Thanks!
