### ISSUE TITLE
install-yq.sh is out of date

### ISSUE THREAD

**Issue by crobinso** [kata-containers/osbuilder#421]
osbuilder's `scripts/install-yq.sh` is out of date with runtime and tests repo copes. If an end user runs it, it will install a `yq` version that is too old to properly run the CI static-checks for example.

it's easy enough to update it but can we eliminate it all together? Maybe pull down the tests repo and run `make -C ${tests_repo_dir} install-yq` like CI does? Or just print install instructions and exit? That's what was done prior to commit 05428a642407 ; the autoinstall tactic has problems of its own though

**Comment by wainersm** [comment]
The osbuilder's `scripts/install-yq.sh` is also out of sync with packaging. The former installs yq version 2.4, and packaging needs 3.1.0.

Actually packaging yq installer (see `packaging/scripts/lib.sh#install_yq()`) simply calls the `tests/.ci/install_yq.sh` install, ensuring CI and packaging sees the same version. Perhaps osbuilder should do the same, so avoiding the need to sync up yq versions.

References: https://github.com/kata-containers/packaging/issues/1011

**Comment by jodh-intel** [comment]
Need to forward port to 2.0.
