### ISSUE TITLE
Documention about how to run a vm from the result of image-builder

### ISSUE THREAD

**Issue by berlinsaint** [kata-containers/osbuilder#425]
hey, i m using the osbuilder  to build some cloud img that can boot a vm, i found that

thery are lack of the doucmention about using the result of image-builder...

**Describe the solution you'd like**

tell us an demo qemu command that can boot a instance. (use systemd)

**Comment by jodh-intel** [comment]
Hi @berlinsaint - this issues seems to have "falled through the cracks" I'm afraid. I'm not 100% clear what you are asking for but it sounds like you want to run "Kata without Kata"? :smile: Out of interest, why are you trying to do this?

This is all rather "out of scope" for the project, however if you *really* want to do this, you could extract the `qemu` args from the log file:

```
level=info msg="launching /usr/bin/qemu-system-x86_64 with: [-name sandbox-foo -uuid ...
```

Obviously, this is going to be very Kata option-specific and hypervisor specific (and potentially architecture specific too).

The developer guide already explains how to install a custom osbuilder-generated image for Kata to use:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#install-the-rootfs-image

Regarding systemd inside the guest image, that is not something we are planning to support (https://github.com/kata-containers/runtime/issues/2854).

If this gives you what you need, are you happy to close this issue?
