### ISSUE TITLE
Errors related to loop devices

### ISSUE THREAD

**Issue by dcflachs** [kata-containers/osbuilder#428]
So i am having some issues tying to build an image using the stable-1.10 branch with the following command
`sudo make USE_DOCKER=true DEBUG=true DISTRO=ubuntu image`
The build process always fails with a bunch of errors somehow related to the creation or use of loop devices.

<details>
        <summary>Click to expand</summary>

```
ERROR: File /dev/loop23p1 is not a block device
++++ return 1
+++ device=
+++ continue
+++ rmdir /tmp/tmp.bUdfvZsrS6
+++ rm -f /tmp/tmp.rqzjcqHLDN
+++ error 'Could not calculate the required disk size'
+++ local 'msg=Could not calculate the required disk size'
+++ echo 'ERROR: Could not calculate the required disk size'
ERROR: Could not calculate the required disk size
++ disk_size=
++ img_size=2
++ '[' -n '' ']'
++ remaining=2
++ '[' 2 '!=' 0 ']'
++ img_size=128
++ echo 128
+ img_size=128
+ rootfs_img_size=126
+ create_rootfs_image /rootfs /image/kata-containers.img 126 ext4 4096
+ local rootfs=/rootfs
+ local image=/image/kata-containers.img
+ local img_size=126
+ local fs_type=ext4
+ local block_size=4096
+ create_disk /image/kata-containers.img 126 ext4 1
+ local image=/image/kata-containers.img
+ local img_size=126
+ local fs_type=ext4
+ local part_start=1
INFO: Creating raw disk with size 126M
+ info 'Creating raw disk with size 126M'
+ local 'msg=Creating raw disk with size 126M'
+ echo 'INFO: Creating raw disk with size 126M'
+ qemu-img create -q -f raw /image/kata-containers.img 126M
+ OK 'Image file created'
+ local 'msg=Image file created'
+ echo '[OK] Image file created'
[OK] Image file created
+ info 'Creating partitions'
+ local 'msg=Creating partitions'
+ echo 'INFO: Creating partitions'
+ parted -s -a optimal /image/kata-containers.img -- mklabel msdos mkpart primary ext4 1M -1M
INFO: Creating partitions
+ OK 'Partitions created'
+ local 'msg=Partitions created'
+ echo '[OK] Partitions created'
[OK] Partitions created
++ setup_loop_device /image/kata-containers.img
++ local image=/image/kata-containers.img
+++ losetup -P -f --show /image/kata-containers.img
++ device=/dev/loop24
++ partprobe -s /dev/loop24
+++ seq 1 5
++ for _ in $(seq 1 5)
++ '[' -b /dev/loop24p1 ']'
++ sleep 1
++ for _ in $(seq 1 5)
++ '[' -b /dev/loop24p1 ']'
++ sleep 1
++ for _ in $(seq 1 5)
++ '[' -b /dev/loop24p1 ']'
++ sleep 1
++ for _ in $(seq 1 5)
++ '[' -b /dev/loop24p1 ']'
++ sleep 1
++ for _ in $(seq 1 5)
++ '[' -b /dev/loop24p1 ']'
++ sleep 1
++ error 'File /dev/loop24p1 is not a block device'
++ local 'msg=File /dev/loop24p1 is not a block device'
++ echo 'ERROR: File /dev/loop24p1 is not a block device'
ERROR: File /dev/loop24p1 is not a block device
++ return 1
+ device=
+ die 'Could not setup loop device'
+ error 'Could not setup loop device'
+ local 'msg=Could not setup loop device'
+ echo 'ERROR: Could not setup loop device'
ERROR: Could not setup loop device
+ exit 1
make: *** [Makefile:123: /tmp/osbuilder/kata-containers.img] Error 1

```
</details>

**Comment by dcflachs** [comment]
To reproduce try the following.
Build a docker container 
`FROM docker:dind` adding in the following packages in `make, go ,git, gcc, curl, bash and sudo` and an entry point script as follows 
```
#!/bin/sh
dockerd-entrypoint.sh &>/dev/null & /bin/sh
```
run the container with 
```
docker run --rm --privileged -it image_name
```

within the container clone the repo to the folder of your choice, checkout stable-1.10 and attempt to build with the command i mentioned in my first post.

```
sudo make USE_DOCKER=true DEBUG=true DISTRO=ubuntu image
```

**Comment by devimc** [comment]
ohh I see you use *dind* to build the images, IMO this too much and maybe out of osbuilder's scope ... ?

cc @grahamwhaley @jodh-intel

**Comment by dcflachs** [comment]
Indeed, I am attempting to find a way to use osbuilder completely from within a container as the system i am on lacks an easy way to install make, go, and git.

**Comment by jodh-intel** [comment]
```
/dev/loop24p1
         ~~
        /
      Wow!
```

I do tend to agree with @devimc - osbuilder really wasn't designed for that environmnent.

/cc @jcvenegas for his thoughts on "running osbuilder inside docker inside docker" ;)

That said, have you tried this with `master`?

**Comment by dcflachs** [comment]
I have not tried with master as i was attempting to get a "released" build going, but i can try that next. Regarding the snippet above, is 24 loop devices not a common thing for the osbuilder? Because I only 4 of those devices are created by my host system (or docker for that matter) the remaining 20 are created during the make process. 

I went the docker in docker route as it seemed the easiest as your current build in docker method still has dependencies on the host system other than docker. In retrospect it may have made more sense to try and run the non-docker build process within a container but I was having difficulty finding specifically what was needed to configure the build environment.

**Comment by jcvenegas** [comment]
@dcflachs this a case we dont have in mind, could you add a line that actually to check if the block device actually was created in the container, also how far it goes if you just run sudo make USE_DOCKER=true DEBUG=true DISTRO=ubuntu image inside your host (without  docker in docker)

**Comment by dcflachs** [comment]
@jcvenegas 

> could you add a line that actually to check if the block device actually was created in the container
I am not sure what this would look like honestly. Using losetup both on the host and in the container I can see many loop devices being created.

> how far it goes if you just run sudo make USE_DOCKER=true DEBUG=true DISTRO=ubuntu image inside your host (without docker in docker)
Unfortunately the whole reason I am trying to use a strange docker setup is that I do not have git, make, go, or sudo (though sudo is not required as I am root on the host) available on this particular host, only docker.

**Comment by dcflachs** [comment]
> That said, have you tried this with `master`?
Building with Master, as of yesterdays commit 891b61c993a02d16a4d791dfdd9c6b1644f52669 fails in the same way.

**Comment by skaegi** [comment]
Is there anyway I could help make progress on this or get help to understand the problem. Unfortunately using dind or buildkit is the only way we can run automated docker build style work loads. Can we do some pre-setup to make osbuilder happy?

**Comment by devimc** [comment]
@skaegi I found a way to have this working, the key is to run the first docker container(L0) with `-v /dev:/dev --privileged --cap-add SYS_ADMIN`

**Comment by skaegi** [comment]
Awesome thank-you -- that worked perfectly! Also not totally terrifying as I just built it in a dind in a kata vm.

**Comment by skaegi** [comment]
hmm... actually i just realized i was mounting /dev from the real host *gulp* (scary). Is there any clever way to mount /dev from the guest os?

**Comment by devimc** [comment]
are you using kata as L0 ?  if that's the case,  I guess `-v /dev:/dev` is not needed... ?

**Comment by ariel-adam** [comment]
Closing this issue since there is a workaround.
