### ISSUE TITLE
/osbuilder/rootfs.sh: line 154: make: command not found

### ISSUE THREAD

**Issue by liyingjun** [kata-containers/osbuilder#43]
When building rootfs for centos using command:
export USE_DOCKER=true
./rootfs-builder/rootfs.sh -r "${PWD}/centos_rootfs" centos

failed with: /osbuilder/rootfs.sh: line 154: make: command not found

**Comment by bergwolf** [comment]
Hi @liyingjun, I can confirm the error locally and I see that you already have a patch for it. Can you please make a PR? Thanks!

**Comment by liyingjun** [comment]
@bergwolf  PR https://github.com/kata-containers/osbuilder/pull/40 fixes the issue

**Comment by jodh-intel** [comment]
Closing as it sounds like the issue is now resolved.
