### ISSUE TITLE
Add method to build customer (QAT) rootfs and kernel

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/osbuilder#440]
**Which feature do you think can be improved?**

We have [QAT build instructions](https://github.com/kata-containers/documentation/blob/master/use-cases/using-Intel-QAT-and-kata.md), but it is still somewhat laborious to extract the info from there to build a modified rootfs and kernel...

Hoik that info out and automate it.

**Comment by jodh-intel** [comment]
Need to forward port to 2.0.
