### ISSUE TITLE
Cannot disable the use of chronic on test_images.sh

### ISSUE THREAD

**Issue by wainersm** [kata-containers/osbuilder#447]
`test_images.sh` will always try to use `chronic` regardless of `OSBUILDER_USE_CHRONIC` being set off. The same behavior (i.e. chronic is always called) can be seen either calling `test/test_image.sh` or `make test`.

See on following snipped that `OSBUILDER_USE_CHRONIC` is always set to `1`
```
# export OSBUILDER_USE_CHRONIC=0
# echo $OSBUILDER_USE_CHRONIC
0
# ./tests/test_images.sh 
INFO: Running with KATA_DEV_MODE set, skipping installation of docker and kata packages
INFO: Running tests for all distros
INFO: building rootfses with systemd as init: centos clearlinux debian euleros fedora suse ubuntu
INFO: building all rootfses with kata-agent as init
INFO: Starting make with 
	# of // jobs:  8 
	targets:       rootfs-centos rootfs-clearlinux rootfs-debian rootfs-euleros rootfs-fedora rootfs-suse rootfs-ubuntu 
	variables:     USE_DOCKER=true DOCKER_RUNTIME=runc ROOTFS_BUILD_DEST=/tmp/osbuilder-test.wPBuKd6/rootfs-osbuilder IMAGES_BUILD_DEST=/tmp/osbuilder-test.wPBuKd6/images DEBUG=1 GRACEFUL_EXIT=1 OSBUILDER_USE_CHRONIC=1
INFO: Starting make with 
```

Digging into `test_images.sh` source, It seems that OSBUILDER_USE_CHRONIC isn't even used. Instead it uses `DEBUG`:

```
# Run a command in silent mode using chronic.
# The command output is printed only if the command fails
silent_run()
{
        typeset -a commandLine=("$@")
        info "running: ${commandLine[@]}"
        if [ -z "${DEBUG:-}" ]; then
                chronic "${commandLine[@]}"
        else
                "${commandLine[@]}"
        fi
}
```

If I exported `OSBUILDER_USE_CHRONIC=0` I would expect it to turn off chronic although this feature isn't documented. Or this toggle can be completely removed.

**Comment by wainersm** [comment]
@grahamwhaley @jcvenegas hi guys!
I opened this months ago just before having a better understand of the project. It seems that although this `OSBUILDER_USE_CHRONIC` variable isn't used indeed, this isn't a big deal. So if you guys agree I will close it to reduce the pile of issues.

**Comment by jodh-intel** [comment]
@wainersm - thanks - I'll close it now, but feel free to reopen if required...
