### ISSUE TITLE
XFS (pmem1): DAX and reflink cannot be used together!

### ISSUE THREAD

**Issue by devimc** [kata-containers/osbuilder#455]
disable reflink for xfs

**Comment by amshinde** [comment]
@devimc Can you add some more details to this issue? What errors were you seeing when using pmem device?

**Comment by devimc** [comment]
@amshinde 

> XFS (pmem1): DAX and reflink cannot be used together! 

I only see this

**Comment by fidencio** [comment]
@amshinde , @devimc, the limitation is mentioned in the mkfs.xfs manual page: http://man7.org/linux/man-pages/man8/mkfs.xfs.8.html

```
                          Note: the filesystem DAX mount option ( -o dax )
                          is incompatible with reflink-enabled XFS
                          filesystems.  To use filesystem DAX with XFS,
                          specify the -m reflink=0 option to mkfs.xfs to
                          disable the reflink feature.
```

**Comment by amshinde** [comment]
@fidencio Thanks for the reference!

**Comment by jodh-intel** [comment]
Need to forward port to 2.0.
