### ISSUE TITLE
building euleros based rootfs inside docker failed

### ISSUE THREAD

**Issue by ChenQi1989** [kata-containers/osbuilder#459]
command:
sudo -E AGENT_INIT=yes USE_DOCKER=true SECCOMP=no ./rootfs.sh euleros

error:
/bin/sh: line 1:     6 Floating point exception(core dumped) yum -y update

more detailed output:
Retrieving key from http://developer.huawei.com/ict/site-euleros/euleros/repo/yum/2.2/os/RPM-GPG-KEY-EulerOS
Importing GPG key 0x381D7AC3:
 Userid     : "EulerOS (EulerOS 2.0 SP2) <EulerOS@huawei.com>"
 Fingerprint: d96f 7aa3 52e2 89c2 8d5d 6cce 6003 17bc 381d 7ac3
 From       : http://developer.huawei.com/ict/site-euleros/euleros/repo/yum/2.2/os/RPM-GPG-KEY-EulerOS
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : libgcc-4.8.5-4.h6.x86_64                                   1/187 
  Updating   : tzdata-2019b-1.noarch                                      2/187 
  Updating   : ncurses-base-5.9-13.20130511.h5.noarch                     3/187 
  Updating   : bash-4.2.46-28.h4.x86_64                                   4/187 
  Updating   : glibc-common-2.17-111.h43.x86_64                           5/187 
  Updating   : nss-softokn-freebl-3.36.0-5.h2.x86_64                      6/187 
  Updating   : glibc-2.17-111.h43.x86_64                                  7/187 
  Updating   : nspr-4.19.0-1.x86_64                                       8/187 
  Updating   : nss-util-3.36.0-1.x86_64                                   9/187 
  Updating   : libstdc++-4.8.5-4.h6.x86_64                               10/187 
  Updating   : ncurses-libs-5.9-13.20130511.h5.x86_64                    11/187 
  Updating   : libdb-5.3.21-19.h2.x86_64                                 12/187 
  Updating   : bzip2-libs-1.0.6-13.h4.x86_64                             13/187 
  Updating   : audit-libs-2.4.1-5.h1.x86_64                              14/187 
  Updating   : elfutils-libelf-0.163-3.h5.x86_64                         15/187 
  Updating   : sed-4.2.2-5.h4.x86_64                                     16/187 
  Updating   : libcom_err-1.42.9-9.x86_64                                17/187 
  Updating   : lua-5.1.4-14.h1.x86_64                                    18/187 
  Updating   : libgcrypt-1.5.3-13.1.h1.x86_64                            19/187 
  Updating   : libuuid-2.23.2-33.0.1.2.h5.x86_64                         20/187 
  Updating   : file-libs-5.11-31.h2.x86_64                               21/187 
  Updating   : expat-2.1.0-10.h4.x86_64                                  22/187 
  Updating   : elfutils-libs-0.163-3.h5.x86_64                           23/187 
  Updating   : sqlite-3.7.17-8.h5.x86_64                                 24/187 
  Updating   : nss-softokn-3.36.0-5.h2.x86_64                            25/187 
  Installing : libidn2-2.0.5-1.h1.x86_64                                 26/187 
  Updating   : 1:findutils-4.5.11-5.h1.x86_64                            27/187 
  Updating   : p11-kit-0.23.5-3.x86_64                                   28/187 
  Updating   : euleros-release-2.0SP2-10.x86_64                          29/187/bin/sh: line 1:     6 Floating point exception(core dumped) yum -y update
The command '/bin/sh -c yum -y update && yum install -y     autoconf     automake     binutils     chrony     coreutils     curl     gcc     gcc-c++     git     glibc-common     glibc-devel     glibc-headers     glibc-static     glibc-utils     libstdc++-devel     libstdc++-static     m4     make     sed     tar     vim     which     yum' returned a non-zero code: 136

**Comment by devimc** [comment]
euleros was skipped long time ago [1] due to there were no maintainers for fixing its issues, @ChenQi1989 are you willing to take this?


[1] https://github.com/kata-containers/osbuilder/pull/239

**Comment by ChenQi1989** [comment]
@devimc Yes. I'll check with euleros community to see what's going on there.

**Comment by devimc** [comment]
@ChenQi1989 any update on this?, 

closing - please feel free to reopen it if you are willing to work on this
