### ISSUE TITLE
travis stop build when building euleros

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/osbuilder#46]
Sometimes when euleros tests is being executed by travis, it stops all the ci because not output in more than 10 minutes.

See:

https://travis-ci.org/kata-containers/osbuilder/builds/333273461

**Comment by jodh-intel** [comment]
@liangchenye - is this something you could take a look at?

**Comment by liangchenye** [comment]
I think `euleros` is never built in 'travis', we built 'fedora' four times'.

**Comment by liangchenye** [comment]
My first impression of this bug is maybe the network connection of euleros hosted server is not in favor of 'travis'. But in  `tests/image_creation.bats`, it is more like 'building fedora 4 times' takes more than 10 minutes.

Another question is: should we build it in 'travis'? If we have more distros supported in the future, 10 minutes is not enough.

I also comment in #40

**Comment by liangchenye** [comment]
I modified two lines in my commit, it works. https://travis-ci.org/liangchenye/osbuilder/jobs/333580864, the summary is:
```
not ok 1 Can create fedora image
ok 2 Can create clearlinux image
not ok 3 Can create centos image
ok 4 Can create euleros image
```
I did not fix bugs in building fedore and centos and 'building euleros' do takes more time in my testing. 

My fix is totally covered by #40.

**Comment by liangchenye** [comment]
sorry for the wrong comments, https://travis-ci.org/kata-containers/osbuilder/builds/333273461 is already built on the fixes. It is timeout issue.

**Comment by jodh-intel** [comment]
Hi @jcvenegas, @liangchenye - Travis itself won't ever timeout it seems (https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts). Clearly, we want the CI tests to run "in a reasonable amount of time". However, another solution might be to make the tests a little "noisier" (verbose output). If they are timing out downloading packages, can't we just run the package-management tool in verbose/debug mode to show download progress? As long as *some* output is shown within a 10 minute perior, Travis shouldn't fail the jobs.

Note: we don't plan to use Travis forever - we can't, as it doesn't provide VT-x support. So at some point (soon) we'll switch to an alternative. This will probably be Jenkins-based, as we use that for Clear Containers currently (http://cc-jenkins-ci.westus2.cloudapp.azure.com/).

**Comment by liangchenye** [comment]
The silence is caused by 'bats'. It won't generate the `info/error` message util the whole job finished.

**Comment by liangchenye** [comment]
It is not stable, sometimes , it only takes `Ran for 8 min 41 sec`.
https://travis-ci.org/liangchenye/osbuilder/builds/333677748

**Comment by jcvenegas** [comment]
@jodh-intel  @liangchenye , yes   is bats silence , I went to travis docs and now found  a way to increase that time. Now seems all works OK.
