### ISSUE TITLE
 Add kernel builder script

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/osbuilder#6]
The script should manage:
- config
- fetch latest kernel from kata-containers/linux

**Comment by jcvenegas** [comment]
@sameo @devimc @laijs, I'd like to automate the process to build kata kernel.

Based in comments from https://github.com/kata-containers/linux/pull/5 we may want:

- We want to have the configuration files in osbuilder tree.
- The automation will pull the latest kata kernel 
- Will use the user desired configuration (kernel config)
- Build a kernel !

## What kernel formats we want to support ?
I consider vmlinux and vmlinuz (compressed and decompressed)

## Do we want to support for kernel modules ?
IMO the kata kernel should not ship modules, all the need features would be built-in. This will make easy use the kernel independently of the guest image. 

```
# Download the kernel
./kernel-builder fetch-kernel
```
Here I have in mind two ways: 
- Tag kata/linux repository and pull the latest tag from this repository (which have all the need patches for Kata kernel)

- Have a file to save the latest kernel version we support 
   - Download the kernel source from kernel.org or kernel repository and apply on top of it the config and the kernel patches for kata. 

Then build the kernel:
```
# Download the kernel
./kernel-builder build-kernel
```
This will build the downloaded and configured kernel from `./kernel-builder fetch-kernel`

**Comment by bergwolf** [comment]
Why should not kata kernel ship modules? Kernel features can be optional and we can keep optional modules separate without the need to load them at boot. It keeps the kernel size small as well as boosts kernel image loading.

**Comment by bergwolf** [comment]
@grahamwhaley yes we did and it seems we have not reached an agreement. We can enable module crc to have a minimal checking, or enable module signing if we care that much.

We should ship a list of modules we want to support and users are supposed to use them only. Users are responsible for their own actions inside a container and pay if they install a hacked module other than the ones provided by us. At the least, whatever modules loaded by a user only affect one guest.

**Comment by grahamwhaley** [comment]
I think we can break this down into a couple of stages/decisions...

1) I think if we enable module support we should also enable module versioning (`CONFIG_MODVERSIONS=y`) to try and prevent anybody loading a module that was not built for/against the actual kernel running. That is mostly to stop silly hard to debug errors :-). We should try to ensure that every kernel we build (at least with a different config file) has a different release strings to help enforce this (/cc @jcvenegas)
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/module-signing.rst#n281

1) I agree @bergwolf that we should probably at least list the modules that we have tested that work :-)

1) We should decide if we want to enable module signing as a security measure to stop anybody loading corrupted or hacked modules. I think we can delay that for a later day, and maybe make it a kernel/osbuilder build time decision for 'extra secure kata containers' etc.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/module-signing.rst

**Comment by bergwolf** [comment]
@grahamwhaley Yes, I agree your all points. I just wanted to make sure we have module support and  have a build/ship mechanism for modules ;) All the security considerations sound good to me.

**Comment by jcvenegas** [comment]
@bergwolf @grahamwhaley  thank you for the comments, I miss the discussion about modules in linux PR. I was afraid of having a dependency between kernel and image. All the points sounds fair. 

Collecting information about it modules discussion: 

I see two points:

- Optional features are built as modules. 
 crypto, nfs, vsock, ipv6, l2tp etc. 
 They are not essential to run a pod and are not loaded if unneeded.
Do we have a complete list of modules we want as module ( It would be great if they really increase a lot the kernel size and boot time) ?

- Provide loadable modules opens up the opportunity to provide guest modules if the default kernel config misses something important to a user.

**Comment by grahamwhaley** [comment]
For the list of modules to build by default, let's collate the needs from both CC and runv.
@egernst @mcastelino do you have some known needs for items you'd like to have available as modules?
@bergwolf , similarly, if you have items you know you want as modules can you list them here pls.

Then we can enable `MODULES` and `MODVER` in our default `.config` and add `=m` to the items on the list as a start. Then if/as we find more items are being requested regularly as modules we can update the default `.config`. We should also document how a user (can use `osbuilder`? to) build their own module to match the kernel if they need.

**Comment by egernst** [comment]
I know i40e offhand, but there may be others I'll need -- will follow up, likely on another issue.

**Comment by jodh-intel** [comment]
Hi @jcvenegas - I think we're going to need to look at this again as we move towards [packaging Kata](https://github.com/kata-containers/packaging/issues/1).

/cc @egernst.

**Comment by jodh-intel** [comment]
## Kernel configs

After the kernel config wiki page was created:

- https://github.com/kata-containers/community/wiki/Document-essential-kernel-config-options-for-ppc64le,-arm64-and-x86_64
  (currently empty - hint to all! :)

... I started looking at the kernel configs we currently have in the packaging repo:

- https://github.com/kata-containers/packaging/tree/master/kernel/configs

... and I found the following (which I'm assuming was an oversight):

```
$ cd $GOPATH/src/github.com/kata-containers/packaging
$ grep "^CONFIG.*=m" kernel/configs/*4.14.x | cut -d: -f2- | sort -u | wc -l
11                              
```

## Random thought

osbuilder creates a YAML file inside the image with details about the image. I'm wondering if we want to do something similar for the assets that live outside the image, one of which is the kernel. We could create something like:

-  `/usr/share/kata-containers/vmlinux-${version}-container.yaml`

    Containing:

    - full timestamp when file created.
    - the sha512 hash of the file (generated by osbuilder)
    - native architecture of the kernel.
    - a list of all the `CONFIG_` options used to build the kernel for the current platform.

- `/usr/share/kata-containers/kata-containers-image-${version}.img.yaml`

   Containing:

   - full timestamp when file created.
   - the sha512 hash of the file (generated by osbuilder)
   - native architecture of the image.
   - list of embedded kernel modules.

These files wouldn't need to be consumed by the runtime but would be useful for admins / developers.

What's annoying is that I can't see a way to check if a particular pair of files (kernel yaml + image yaml) are compatible. I think the best we could do is get osbuilder to generate a random hash and embed that into both YAML files so you'd atleast know that the pair were build as part of the same osbuilder run (and where tested together and hence should be compatible). Something like having the following in both files:

```
osbuilder-build-id: d0bccabbe133ad25f3bd0297b383baf58eef3c27
```

**Comment by fanux** [comment]
How does kata customize its own kernel version, how to specify the kernel version? Assume that multiple kernels exist simultaneously.

**Comment by jodh-intel** [comment]
> How does kata customize our own kernel version (for example kernel 3.10),

I'm not sure what you really mean here? Kata uses its own guest kernel which is built using the scripts and kernel config files here:

- https://github.com/kata-containers/packaging/tree/master/kernel

> how to specify the kernel version when run vm? Assume that multiple kernels exist simultaneously.

The default guest kernel is pre-configured in the `configuration.toml` file. For example assuming you have **not** created a custom config file (`/etc/kata-containers/configuration.toml`):

```sh
$  crudini --get /usr/share/defaults/kata-containers/configuration.toml hypervisor.qemu kernel
"/usr/share/kata-containers/vmlinuz.container"
```

However, Kata does support using different kernel versions for different containers/pods using "annotations":

- https://github.com/opencontainers/runtime-spec/blob/master/config.md#annotations
- https://github.com/kata-containers/runtime/blob/master/virtcontainers/pkg/annotations/annotations.go#L9..L12

There is ongoing discussion about this. See:

- https://github.com/kata-containers/runtime/issues/1655
- https://github.com/kata-containers/runtime/pull/1695

**Comment by fanux** [comment]
@jodh-intel thank you very much, that is what I need

**Comment by jcvenegas** [comment]
we have already one script in packaging  lets close this.
