### ISSUE TITLE
Add a CI test to create a container with every image

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#68]
The CI currently runs the following, which checks to ensure a rootfs/image/initrd can be created:

- https://github.com/kata-containers/osbuilder/blob/master/tests/image_creation.bats

We need to create a new test that will:

- Install the system components

 - Create a container:
  ```
  $ sudo docker run -ti --runtime kata-runtime busybox true
  ```

The question is: should we build the components from source or install the packaged components [when available](https://github.com/kata-containers/packaging/issues/1)?

I'm inclined to think we should use the packaged versions since:

- We're assured of stability of those components

  We're trying to test the images on this issue, not the separate components.

- It's simpler to setup.

**Comment by sboeuf** [comment]
@jodh-intel the question is, are we gonna package every images ? If not, we'll have to create our own rootfs/images from the test, in order to be able to test them all.

**Comment by jodh-intel** [comment]
@sboeuf - I'm confused. The test mentioned above already creates an image / distro. But for sake of ease, we could consider installing the packages for the main components (shim, proxy, runtime, guest kernel, hypervisor), but not the image package.

**Comment by sboeuf** [comment]
@jodh-intel Oh yeah I was confused... Nevermind.

**Comment by devimc** [comment]
I think we can close this issue, since we already have a simple test for all images, see https://github.com/kata-containers/osbuilder/blob/master/tests/test_images.sh , please feel free to reopen if I missed something
