### ISSUE TITLE
support to build image/initrd based on existing rootfs

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/osbuilder#69]
Just so that we do not have to re-build rootfs every time for local build/testing.

**Comment by grahamwhaley** [comment]
yes please :-) Also, if using the docker build, it might be nice if we store the base docker image as iirc that gets composed each time as well.

**Comment by bergwolf** [comment]
The base docker image gets rebuilt because it relies on fetching remote files (e.g., the golang binary).

**Comment by grahamwhaley** [comment]
Right, but once we have fetched them once, we could store and re-use that docker image in the local docker image store as long as we can verify nothing has changed in the meantime (like the version of go in use etc.).
iirc, for me right now, every build downloads lots of the same stuff.
Just a thought for the future.
