### ISSUE TITLE
Add support for a non systemd rootfs

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/osbuilder#7]
This requires the agent work as a `init` process for the Guest OS.

**Comment by bergwolf** [comment]
The agent can work as a `init` process right now. The only missing part is reaping zombie children which non-init agent also needs.

**Comment by jcvenegas** [comment]
That is great! @bergwolf  is there a way to quickly test the agent without use the complete Kata stack?

If not would be great to have an cli protocol test to allow the VM works well:

cli-protocol-test  <---> serial port  <----> vm  <---> Agent
