### ISSUE TITLE
kata-containers-image package

### ISSUE THREAD

**Issue by erick0z** [kata-containers/osbuilder#78]
`clear-containers-image` package is built using an osbuilder released image on [github](https://github.com/clearcontainers/osbuilder/releases). I was wondering if we want to build kata-containers-image package this way or using the scripts to generate an image in the build system and then package it.
If the image will be generated from the scripts, it would be cool to have [this PR](https://github.com/kata-containers/osbuilder/pull/63) landed.
If we want packages generated from an official image, then we need to release a stable image on this repository.

What do you think? @jcvenegas @jodh-intel @bergwolf @egernst

**Comment by jodh-intel** [comment]
I think @jcvenegas probably has a good view on this as he wrote the github publishing tooling.

An important consideration is security -  I'm pretty sure that historically OBS didn't allow access via https (absolutely no idea why). However, it does now seem to which puts publishing to OBS on security parity with publishing to github:

- Fedora
  - http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/Fedora_27/home:clearcontainers:clear-containers-3.repo
  - https://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/Fedora_27/home:clearcontainers:clear-containers-3.repo
- Ubuntu
  - http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/xUbuntu_17.10/Release.key
  - https://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/xUbuntu_17.10/Release.key

**Comment by jcvenegas** [comment]
@jodh-intel  @erick0z 
That is a good question for Clear Containers we had a versions file that defined the agent and os version to build the image.

A couple of questions

  - what should the default image flavor that we will provide in our packages? 

The parameters  needed are:
```
[image]
agent=<version>
BASE_OS=<base>
OS_VERSION=<version>
AGENT_INIT=<version>
```
 - Are we going to ship both initrd flavor and raw image? 
My guess is yes ?

 - The CI will use those image we publish ? or should build all the time the image with the previous  data (except the agent version).

IMO the second option sounds better.

So if we choose the image being generated each PR with the latest agent we:
pros:
    - Exercise osbuilder each PR to know is not broken.
    - We test the latest agent all the time
cons:
    - ci will take a bit more time.

Then the only time we may want a image published is  each time new packages are created.
So we may need to generate and publish an image just before create the image package. I'd suggest publish the image in the agent repository with its proper tag. 

So when we create a new package update.

1. Generate the image based on our default image configuration.
2. Depending if is a local bulid or not do:
  A)  If is a local build use that image to generate the package.
  B) If the package will be published, publish the image in agent repository.
      Build the  pkg pointing to that release

**Comment by jcvenegas** [comment]
update: In this initial packaging work the scrips will build the image locally and upload it to obs as source0.

**Comment by devimc** [comment]
closing, we generate the image using osbuilder in OBS
