### ISSUE TITLE
Include `ps` command

### ISSUE THREAD

**Issue by devimc** [kata-containers/osbuilder#81]
kata-runtime should have an implementation similar to [runc](https://github.com/opencontainers/runc/blob/master/ps.go#L63) to list the processes inside the containers.

* `ps` command should be included in all the images generated by `osbuilder`
* document why `ps` command is needed

**Comment by grahamwhaley** [comment]
or presumably we could parse /proc ?

**Comment by devimc** [comment]
@grahamwhaley no we can't, user can specify ps options using docker top, if we read /proc then we have to support **ALL** ps options

```
$ docker top --help
Usage:	docker top CONTAINER [ps OPTIONS]
```

**Comment by devimc** [comment]
**[ps OPTIONS]**

```
$ docker top --help
Usage:	docker top CONTAINER [ps OPTIONS]
```

**Comment by grahamwhaley** [comment]
Agreed. Thanks for explaining - I'd forgotten the user can supply options through `docker top`.
