### ISSUE TITLE
Docker is not running after enabling initrd

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/osbuilder#82]
Running a container is not possible after enabling initrd. It is not possible to enable initrd Jenkins testing (https://github.com/kata-containers/tests/issues/190). The configuration that I used was the following.
$ go get -d github.com/kata-containers/tests
$ cd .ci/
$ export AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=alpine
$ ./setup.sh

After completing the setup of the environment, what I did was
$ docker run --runtime kata-runtime -ti fedora bash

However, the container stays in `created`
$ docker ps -a
CONTAINER ID   IMAGE    COMMAND             CREATED             STATUS              PORTS               NAMES
7b8f56ba6297   fedora      "bash"              19 minutes ago      Created     affectionate_blackwell 

I am using the following configuration:
Ubuntu 16.04.4 LTS
kata-runtime  : 0.0.1
commit   : 427b97c6f53efce2e9a54abf56eff0e75961574d
OCI specs: 1.0.1
Docker version 17.12.1-ce, build 7390fc6

**Comment by GabyCT** [comment]
@bergwolf could you please take a look? thanks

**Comment by bergwolf** [comment]
@GabyCT what I mentioned in kata-containers/tests#190 is just the suggested environment names for test setup. We need to actually add support for these environment variables in kata-containers/tests before it can work.

From osbuilder side, the accepted environments are `DISTRO`, `DISTRO_ROOTFS`, `IMG_SIZE` and `AGENT_INIT`.

The suggested `TEST_INITRD` in kata-containers/tests#190 is to tell the tests to build initrd images and configure initrd images in kata-runtime's configuration file.

**Comment by bergwolf** [comment]
@GabyCT Do you still see the issue? I tried ci setup.sh on one of my test machine, found a new issue (kata-containers/tests/issues/333) and fixed it. Then setup.sh sets up initrd test environment properly. Can you please see if kata-containers/tests/pull/334 works for you?

**Comment by GabyCT** [comment]
@bergwolf , not anymore. This is already fixed as I was able to run integration docker tests.
