### ISSUE TITLE
rootfs.sh: Add "${AGENT_VERSION}"/"-a" functionality 

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/osbuilder#90]
For now, the flag "-a" or relevant shell variant "${AGENT_VERSION}" hasn't been used, only defined.
The `git checkout ${AGENT_VERSION}` command should be after `pushd` when working directory has been set into `GO_AGENT_PKG`.
**COMMAND**:
```
export USE_DOCKER=true
./rootfs-builder/rootfs.sh -r "${PWD}/alpine_rootfs" alpine
```
**RESULTS**:
```
INFO: Pull Agent source code
[OK] Pull Agent source code
INFO: Build agent
~/penny/go/src/github.com/kata-containers/agent /go
Already on 'master'
Your branch is up to date with 'origin/master'.
[OK] Checkout successful
```
Also, a minor typo error for option select in getopts. It should be `a` instead of `c`😝.

**Comment by Pennyzct** [comment]
@weichen81 @jcvenegas  @jodh-intel

**Comment by jodh-intel** [comment]
Thanks @Pennyzct - I've now assigned this to you if you want to raise a PR for the fix.
