### ISSUE TITLE
Create a debug console test

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#96]
We need a test to ensure the debug console works:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#set-up-a-debug-console

**Comment by jodh-intel** [comment]
Related: #97.

**Comment by devimc** [comment]
@jodh-intel probably to test the console you'll need something like this https://gist.github.com/devimc/75f3e6b3172923e104b41b099fc8731a

**Comment by jodh-intel** [comment]
Thanks @devimc! I'll give this a try...

**Comment by jodh-intel** [comment]
https://github.com/kata-containers/documentation/pull/404 reminds me, we *really* need a test for the debug console if someone would like to pick this up...?

There are now two scenarios to test the debug console in: `use_vsock=false` and `use_vsock=true`.

**Comment by jodh-intel** [comment]
Note that we'll need to special-case alpine as that doesn't use systemd.

**Comment by devimc** [comment]
can we close this? we already have a test https://github.com/kata-containers/tests/pull/1539

**Comment by jodh-intel** [comment]
Agreed.
